#开发环境配置
server:
  #端口
  port: 80
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
       url: jdbc:mysql://localhost:3306/daxia?useUnicode=true&characterEncoding=UTF-8&utoReconnect=true
       username: root
       password: root
       driver-class-name: com.mysql.jdbc.Driver